[workspace]
name = "mote"
description = "Development environment for Mote ROS packages"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "linux-aarch64"]

[target.unix.activation]
# For activation scripts, we use bash for Unix-like systems
scripts = ["install/setup.bash"]

[feature.build.target.unix.tasks]
build = "colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY"

[feature.test.target.unix.tasks]
build = "colcon test"

# Dependencies used by all environments
[dependencies]
python = "*"
# Build tools
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
# ROS specific tools
rosdep = "*"
colcon-common-extensions = "*"
# Formatting
clang-tools = "*"

[target.linux.dependencies]
libgl-devel = "*"

[environments]
jazzy = { features = ["jazzy", "build", "test"] }

### ROS Jazzy ####
[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
ros-jazzy-ros-base = "*"
ros-jazzy-ament-cmake = "*"
ros-jazzy-rclcpp = "*"
ros-jazzy-controller-manager = "*"
filelock = "*"
ros-jazzy-control-toolbox = "*"
ros-jazzy-hardware-interface = "*"
ros-jazzy-transmission-interface = "*"
# mujoco_vendor not available on pixi - MuJoCo provided via pypi mujoco package instead
ros-jazzy-position-controllers = "*"
ros-jazzy-robot-state-publisher = "*"
ros-jazzy-xacro = "*"
ros-jazzy-ros2controlcli = "*"
ros-jazzy-ros2-control-cmake = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-std-msgs = "*"
ros-jazzy-urdfdom = "*"
ros-jazzy-urdfdom-py = "*"
ros-jazzy-rviz2 = "*"
ros-jazzy-launch-testing-ament-cmake = "*"
ros-jazzy-joint-state-broadcaster = "*"
ros-jazzy-joint-state-publisher = "*"
ros-jazzy-joint-state-publisher-gui = "*"
ros-jazzy-diff-drive-controller = "*"
# Linting
ros-jazzy-ament-cpplint = "*"
ros-jazzy-ament-cppcheck = "*"
ros-jazzy-ament-flake8 = "*"
ros-jazzy-ament-pep257 = "*"
